### ISSUE TITLE
API Broken, receiving 500

### ISSUE THREAD

**Issue by nitzel** [openpotato/openholidaysapi.website#10]
# Problem 
Api returns 500 instead of result

## expected behaviour
api should return data

## detailed description of issue/reproductions teps

<img width="1212" alt="image" src="https://github.com/openpotato/openholidaysapi.website/assets/8362046/78c0abc3-d7f7-4f51-8640-37f66f40a03d">

### Suggested curl
```
curl -X 'GET' \
  'https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&languageIsoCode=DE&validFrom=2023-01-01&validTo=2023-12-31&subdivisionCode=DE-BE' \
  -H 'accept: text/plain'
```

### URL
```
https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&languageIsoCode=DE&validFrom=2023-01-01&validTo=2023-12-31&subdivisionCode=DE-BE
```

### Response
`500` undocumented

headers
```
 content-length: 0 
 content-security-policy: default-src https: data: 'unsafe-inline' 
 date: Fri,24 Nov 2023 13:09:31 GMT 
 permissions-policy: accelerometer=(),camera=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),payment=(),usb=(),interest-cohort=() 
 referrer-policy: strict-origin-when-cross-origin 
 server: nginx 
 x-content-type-options: nosniff 
 x-frame-options: SAMEORIGIN 
```

**Comment by BlackScreen** [comment]
Yeah, same here. Not working since yesterday.

**Comment by fstueber** [comment]
Please try again. Should work

**Comment by BlackScreen** [comment]
> Please try again. Should work

I did just try - the Countries-endpoint also gives a 500 error.

**Comment by fstueber** [comment]
Ah yes, you both right, I was to fast :-(

**Comment by fstueber** [comment]
Fixed. Please check again.

**Comment by BlackScreen** [comment]
> Fixed. Please check again.

Nope, not working here and also not working in the Swagger-Test. Tested with the Countries-endpoint (as this is the first one in my script that is failing).

**Comment by BlackScreen** [comment]
And now it works again. I just tested it again. My script is running again. Thanks for fixing it! :)

**Comment by nitzel** [comment]
Thanks for fixing! Is this the first time happening? Do you need help with setting up a watcher monitoring for incidents?

**Comment by fstueber** [comment]
Hi @nitzel, the problem was caused by a major update of the development stack (.NET 7 to .NET 8). I have already done this for the sister project OpenPLZ API, without any problems. I didn't expect any problems here either, but unfortunately there were breaking changes in the database layer specific for this project (JSON serialization to/from PostgreSQL). 

About monitoring: There is already one at https://openpotato.github.io/uptime/. It's not perfect, but it's open source and based on GitHub. Of course I'm always curious: What would you recommend for monitoring OpenHoliday's API?

**Comment by nitzel** [comment]
> Hi @nitzel, the problem was caused by a major update of the development stack (.NET 7 to .NET 8). I have already done this for the sister project OpenPLZ API, without any problems. I didn't expect any problems here either, but unfortunately there were breaking changes in the database layer specific for this project (JSON serialization to/from PostgreSQL).
> 
> About monitoring: There is already one at https://openpotato.github.io/uptime/. It's not perfect, but it's open source and based on GitHub. Of course I'm always curious: What would you recommend for monitoring OpenHoliday's API?

That looks great - did you get a notification for the incident? We've set up StatusCake to get Slack messages once a service is down, but it looks like your solution should already work.
