### ISSUE TITLE
Bug in https://openholidaysapi.org/SchoolHolidays?

### ISSUE THREAD

**Issue by tim-sadler** [openpotato/openholidaysapi.website#11]
The following get command does not work as of today:  https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&subdivisionCode=DE-HH&languageIsoCode=EN&validFrom=2022-10-01&validTo=2023-11-30

(Tried with the official API test tool)

**Comment by fstueber** [comment]
Fixed. Not everything was published in time.
