### ISSUE TITLE
Semesterferien Österreich fehlen 

### ISSUE THREAD

**Issue by rtwl21** [openpotato/openholidaysapi.website#13]
die Semesterferien welche nicht Landesweit gültig sind fehlen in der Liste der Schulferien.
kann man diese implementieren?

**Comment by fstueber** [comment]
Hallo. Semesterferien werden mit ausgegeben. Beispiel: 

```
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31
```

Oder ist etwas anderes gemeint?

**Comment by rtwl21** [comment]
du hast recht, hier sind sie drinnen.
hier aber nicht:
`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&subdivisionCode=AT-3&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31`

oder mach ich einen Fehler?

**Comment by fstueber** [comment]
Der Aufruf muss heißen:
```
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31&subdivisionCode=AT-N%C3%96
```
Der subdivisionCode ist nicht der IsoCode, da nicht alle Subdivisions (über alle Staaten gesehen) einen ISO-Code haben, sondern der Code, wie er von 
```
https://openholidaysapi.org/Subdivisions?countryIsoCode=AT&languageIsoCode=DE
```
ausgegeben wird.

**Comment by fstueber** [comment]
Ach ja:
``` 
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&languageIsoCode=DE&validFrom=2024-01-01&validTo=2024-12-31&subdivisionCode=AT-NÖ
```
klappt natürlich auch (also ohne explizites URL-Encoding von Ö) :-)

**Comment by rtwl21** [comment]
Perfekt danke.
ich bin davon ausgegangen, dass ich den ISO nehmen muss, weil ja früher das Ö in der URL nicht funktionierte.

danke. Jetzt passt alles 👍

hast du zufällig auch was mit iobroker zu tun und könntest damit einen Adapter machen? 🙈😊
dann müsste ich nicht mit dem herumscripten anfangen.

**Comment by fstueber** [comment]
Sorry, habe leider nichts mit iobroker zu tun.

**Comment by rtwl21** [comment]
kein Problem.

du hast übrigens in der Anleitung auch den subdivisionCode AT-2 angegeben. Von dort hab ich das. Vermutlich solltest du das dort ausbessern 😉

`https://openholidaysapi.org/SchoolHolidays?countryIsoCode=AT&subdivisionCode=AT-2&languageIsoCode=EN&validFrom=2022-01-01&validTo=2022-12-31`

**Comment by fstueber** [comment]
Oh je, stimmt. Danke für den Hinweis!
