### ISSUE TITLE
Repetable events status

### ISSUE THREAD

**Issue by peterreiser** [openpotato/openholidaysapi.website#14]
Hi - 
I suggest following enhancements 

The system  should  include an option for specifying the repetition status of a calendar entry.

example: Microsoft outlook:

  "pattern": {
    "type": "absoluteYearly",
    "interval": 1,
    "dayOfMonth": 15,
    "month": 4
  }

**Comment by fstueber** [comment]
Hello, all holiday entries are designed as one-off entries. Of course, public holidays such as Christmas are always on the same day, but there is a separate entry for each year.
