### ISSUE TITLE
Translation issue in Croatian

### ISSUE THREAD

**Issue by jazz-it** [openpotato/openholidaysapi.website#16]
Hi, I've just noticed your Croatian translation for the winter school holiday is off: currently you have a weird combination of an adjective in the genitive with a noun in the nominative - it's not "Zimskoga odmor", but instead it should be "Zimski odmor".

**Comment by fstueber** [comment]
Fixed. Thanks for the feedback. Unfortunately my croatian is very, very bad 😄

**Comment by jazz-it** [comment]
Hi again, Frank! I want to inform you that I just released my own project that relies on your API service and published it here: https://github.com/jazz-it/dline

I added credits by stating the name of the main website and leaving a link to this GitHub project, but if you'd like me to change anything reg. that information, please let me know. Thank you!

**Comment by jazz-it** [comment]
> Maybe a direct link to the project website would be nice.

Done. I hope you'll succeed to cover all the countries one day.

**Comment by fstueber** [comment]
Great. Thanks! Yes, there are still some countries left :-)
