### ISSUE TITLE
JavaScript Library

### ISSUE THREAD

**Issue by Dlurak** [openpotato/openholidaysapi.website#17]
The docs include a list of libraries [here](https://www.openholidaysapi.org/en/libraries/)
I've created a JavaScript/TypeScript library, could it be included?

Here are some links:
- [GitHub](https://github.com/Dlurak/open-holiday-js)
- [NPM](https://www.npmjs.com/package/open-holiday-js)
- [Documentation](https://dlurak.github.io/open-holiday-js/)

**Comment by fstueber** [comment]
Done. Please check.

**Comment by Dlurak** [comment]
Seems good, thanks
