### ISSUE TITLE
Any chance we can add more countries? 

### ISSUE THREAD

**Issue by thabo-moyo97** [openpotato/openholidaysapi.website#2]
Specifacally Hong Kong, Canada and maybe UK? Although, UK has it's own free API.. it is just nice to have everything in one place.

P.S, happy to contribute to do this.

**Comment by fstueber** [comment]
Hi, thanks for feedback. OpenHolidaysApi is open for EVERY country. However, I am currently focusing on countries in Europe. So UK is definitely on my list. However, I would welcome contributions for other non-European countries. If you want to help out, I'm here to guide you.

**Comment by fstueber** [comment]
Also, UK has as for as I know no API for school holidays, only for public/bank holidays

**Comment by thabo-moyo97** [comment]
Sure thing, please guide me and I will add them :)

**Comment by thabo-moyo97** [comment]
Brilliant. I will have a look at this some time this week.

Wanted to ask if there's a way you can use versions? I have built I client based on the structure you produced before the latest update. It is serialised and since you changed the PublicHolidays structure it will error. Maybe best work with versions otherwise maintaining will be difficult.

**Comment by fstueber** [comment]
Hi. What was the breaking change for you? Newest API version got two new endpoints but no change for the existing enpoints. And yes, API versioning is on my list.

**Comment by BlackScreen** [comment]
This makes sense. But I think something in that behaviour changed, because it "broke" my script that evening after you added the new endpoints. Not bad at all, the data is more correct now. I just had to change my script to check if subdivisions are there in the first place. So all good. Just thought the problem of the other user was the same. :)

**Comment by viniciusdeliz** [comment]
@fstueber I would like to collaborate adding holidays for Brazil, would it be possible?

The most reliable and official source that I found for now is https://feriadosbancarios.febraban.org.br/, which is a representative entity of all the banks that operate in Brazil. There's also a more specific list for municipal holidays, not sure if they would be included as subdivisions or something like that. Thanks in advance

**Comment by fstueber** [comment]
Hi. Yes, sure, I would love have Brazil as supported country. Currently I am focused on European countries, but this project is open for every country. I have created a new issue for further discussiion: https://github.com/openpotato/openholidaysapi.data/issues/88
