### ISSUE TITLE
Mistake in date for the Estonian public holidays 2024

### ISSUE THREAD

**Issue by ottkaal** [openpotato/openholidaysapi.website#21]
Hi!

This is not about any problem in code, but something that I found in data. For the Estonian public holidays in 2024 the system is responding with the JSON that contains wrong date of the Pentecost public holiday. It says 2024-06-19 for the Pentecost, but actually the correct date would be 2024-05-19. The web page says that the source for the Estonian public holidays is https://www.eesti.ee/en/republic-of-estonia/republic-of-estonia/national-public-and-school-holidays . But when opened, one can see that there is the correct May 19th date, not the June date as the API claims. Could it be corrected somehow?

![image](https://github.com/openpotato/openholidaysapi.website/assets/169990644/4ad67534-a23f-456f-9535-946ff9d7e3eb)
![image](https://github.com/openpotato/openholidaysapi.website/assets/169990644/313c6662-4055-4107-8fcf-fbf408d9c3f7)

Kind regards,

Ott Kaal

**Comment by fstueber** [comment]
Hi, yes that's a bug in data. Will fix asap. The raw data source is:

https://github.com/openpotato/openholidaysapi.data/blob/7267519b61c4ea82a479bc99fcb4215e22124028/src/ee/holidays/holidays.public.csv#L55

If you find more incorrect data here, please do report. I would be more than happy to fix it.

**Comment by fstueber** [comment]
Fixed. Please check.

**Comment by ottkaal** [comment]
Hi Frank!

Yes, it looks good now:

![image](https://github.com/openpotato/openholidaysapi.website/assets/169990644/09ab26af-4485-4e26-bfd9-ca266f9664a6)

Thank you very much for the quick fix! :)

Kind regards,

Ott
