### ISSUE TITLE
Love the project

### ISSUE THREAD

**Issue by FlipFlop17** [openpotato/openholidaysapi.website#3]
It's not an issue but a question XD.
How and where do you collect data from? 
I am building the same thing as a portfolio/practice project and  I was wondering whats the fastest way to update data year after year ?

**Comment by fstueber** [comment]
Hi. Two things are important:

- **Documentation:** Documentation of the original data sources (laws, regulations, ministry websites, etc.). This makes it easy to check for new data on a regular basis.
- **Community:** One goal is to build a community around this project that will do at least some of the data provision/monitoring.

Feel free to ask more :-)

**Comment by FlipFlop17** [comment]
Thanks! I am proficient in UiPath so I was thinking of creating a scraper
so it can scrape periodically and update my data.
But in any case, yea thought so..look around to scrape everything together
