### ISSUE TITLE
Wrong local swiss holiday for Municipality of Morschach

### ISSUE THREAD

**Issue by Chasum** [openpotato/openholidaysapi.website#32]
The holiday Gallus Day (16 October) is not a holiday of the Municipality of Morschach (District Schwyz).
It is a local holiday for the Municipality Hochwalden in District Solothurn.

**Comment by fstueber** [comment]
I got this information from: https://www.sz.ch/public/upload/assets/8543/Titelblatt_Inhalt_weg_rtg_V2R2.pdf

![image](https://github.com/user-attachments/assets/79b650dd-2e1c-4c2f-adee-055f0990922b)

**Comment by fstueber** [comment]
About Hochwalden (District Solothurn): Any link to this information?

**Comment by Chasum** [comment]
My error. Didn't know it was also holiday in Morschach.

Regarding Hochwald.

https://www.ejpd.admin.ch/dam/bj/de/data/publiservice/service/zivilprozessrecht/kant-feiertage.pdf.download.pdf/kant-feiertage.pdf

![image](https://github.com/user-attachments/assets/2b03ccb9-0167-4fae-a5b0-aa7e61a04e08)

**Comment by fstueber** [comment]
Thanks. I somehow overlooked it. Will add.
