### ISSUE TITLE
October 31 missing as a holiday in Germany (Hamburg)

### ISSUE THREAD

**Issue by TobiasDummschat** [openpotato/openholidaysapi.website#6]
# How to reproduce
## Steps
Call this URI to get the public holidays in Hamburg (Germany) between 2023-10-01 and 2023-11-01:
```
https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&languageIsoCode=DE&subdivisionCode=DE_HH&validFrom=2023-10-01&validTo=2023-11-01
```

## Excepted result

A list containing two holidays: 2023-10-03 and 2023-10-31.

## Actual result

A list containing one holiday: 2023-10-03
```json
[{"id":"f4f1fe82-cd70-4d33-b456-f78f9b77f064","startDate":"2023-10-03","endDate":"2023-10-03","type":"Public","name":[{"language":"DE","text":"Tag der Deutschen Einheit"}],"nationwide":true}]
```

# Context

The missing date 2023-10-31 (reformation day) is not a nationwide public holiday in Germany. It has been a regional public holiday for some German states since the German reunification. It became a public holiday in Hamburg and a few more German states in 2018 and is now listed in your data source for Hamburg ([Gesetz über Sonntage, Feiertage, Gedenktage und Trauertage (FeiertG HA)](https://www.landesrecht-hamburg.de/bsha/document/jlr-FeiertGHAV3P1)). I believe the other states that added it are Bremen, Niedersachsen (Lower Saxony), and Schleswig-Holstein.

**Comment by fstueber** [comment]
Hi, thanks for feedback. You have to change your request a little bit (`DE-HH` instead of `DE_HH`):

```
https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&languageIsoCode=DE&subdivisionCode=DE-HH&validFrom=2023-10-01&validTo=2023-11-01
```

**Comment by TobiasDummschat** [comment]
Thanks for the quick answer. That’s a typo on my part. It works properly with `DE-HH`. I’d expect some kind of bad request error in that case, though.
