### ISSUE TITLE
French School Holidays End Date Wrong

### ISSUE THREAD

**Issue by mdt-mft** [openpotato/openholidaysapi.website#7]
Hey Guys. Really cool API, your effort is much appreciated💪. I have noticed that your data for french school holidays is ocasionally wrong, where the end date is off by one day. 

The christmas holiday in france is from the 

StartDate: 2023-12-23 endDate: 2024-01-07

but your api gives the following: 

StartDate: 2023-12-23 endDate: 2024-01-08

https://www.education.gouv.fr/media/119692/download-accessible

https://openholidaysapi.org/SchoolHolidays?countryIsoCode=FR&validFrom=2023-01-01&validTo=2024-12-31

**Comment by fstueber** [comment]
Hi, thanks for the feedback. Indeed, dates seems to be different now. I have fixed school dates. Please check. My source is https://www.education.gouv.fr/calendrier-scolaire-100148. According to this christmas 2023/2024 is from 2023-12-24 to 2024-01-07.

**Comment by mdt-mft** [comment]
Hi, it looks correct now. Impressively quick fix👍
