### ISSUE TITLE
Laravel Package

### ISSUE THREAD

**Issue by NoahNxT** [openpotato/openholidaysapi.website#9]
Hi ,
in case you'd like to know. I've made a Laravel package for your API:
https://packagist.org/packages/noahnxt/laravel-open-holiday-api

Fully bases on your OpenApi Scheme.

**Comment by fstueber** [comment]
Wow, sounds great. Will have a closer look later.

**Comment by NoahNxT** [comment]
@fstueber Any chance you had time to take a closer look? 😅 Any further comments on it? Feel free to make an issue for it if needed

**Comment by fstueber** [comment]
@NoahNxT. Looks very nice. I'm not a php/laravel exporter, so I can't comment on details. If you don't mind, I would include your library as a third party library in the documentation for the next website update.

**Comment by fstueber** [comment]
Ah, one minor thing. It's called OpenHolidays API (not OpenHoliday API). 😄

**Comment by NoahNxT** [comment]
> @NoahNxT. Looks very nice. I'm not a php/laravel expert, so I can't comment on details. If you don't mind, I would include your library as a third party library in the documentation for the next website update.

Sure thing!

**Comment by thabo-moyo97** [comment]
Hi, I have experience in Laravel and had a quick 5-minute look. Overall, pretty good. Everything seems generic and good use of classes. The only downside for me is the lack of tests. The API could fail one day, and you'd only find out in production. 

This one is opinion, so take with a grain of salt, but you could also use Laravel's HTTP packages. I noticed you are using packages that are not really necessary since Laravel already provides the same thing.

**Comment by NoahNxT** [comment]
> Hi, I have experience in Laravel and had a quick 5-minute look. Overall, pretty good. Everything seems generic and good use of classes. The only downside for me is the lack of tests. The API could fail one day, and you'd only find out in production. 
> 
> 
> 
> This one is opinion, so take with a grain of salt, but you could also use Laravel's HTTP packages. I noticed you are using the saloon php package which is not necessary since Laravel already provides the same thing. You're only using it to make request, so may as well use illuminate/HTTP

I'll make tests for it. The reason why I use saloon is for generalization that makes it easily to maintain by also external contributors. 

Saloon gives me also the ability to extend where needed if something changes and record responses in tests to cover on more places.

Saloon is in the Laravel community since the latest year the most common open-source way Of integrating and packaging apis.

But many thanks for the feedback! I'll integrate some tests and make sure that the docs is a bit more extended. 💪
